server:
  port: 8888

# 自定义
db.username: admin
db.password: password
db.url: jdbc:mysql:///coin
db.driverClassName: com.mysql.jdbc.Driver

db2.username: admin2
db2.password: password2
db2.url: jdbc:mysql:///coin2
db2.driverClassName: com.mysql.jdbc.Driver2

# 自定义
username: qj
age: 18
password: admin


# redis配置
redis:
  host: localhost
  port: 6379
  timeout: 5000
  pool:
    minIdle: 10
    maxIdle: 10
    maxTotal: 100
    maxWaitMillis: 5000
    testWhileIdle: true
    testOnBorrow: true
    testOnReturn: true

# kafka配置
spring:
  kafka:
      bootstrapServer: 192.168.123.127:9092,192.168.123.127:9093
      groupId: btse-order01
      topic:
          orderTopic: order-01
          tradeTopic: trade-01
          priceBookTopic-BTSE: pricebook-01
          marketPriceTopic: marketprice-01
          btu: mpt-btu-01
          eth: mpt-etu-01
          bcu: mpt-bcu-01
          ltu: mpt-ltu-01

# thymeleaf模板引擎
  thymeleaf:
    prefix: classpath:/templates
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    content-type: text/html
    #开发时关闭缓存,不然没法看到实时页面
    cache: false

# DB
  datasource:
    name: user
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8
    username: root
    password: guoguo311
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 1
    minIdle: 1
    maxActive: 1
    defaultAutoCommit: false
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false

# 文件上传
  http:
      multipart:
          enabled: true
          max-file-size: 1MB
          max-request-size: 10MB


filepath: /Users/qinjian/Desktop/img/


# mybatis
mybatis:
  check-config-location: true
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mybatis/*Mapper.xml
  type-aliases-package: com.qj.springboot.bean